
export const INITIALSTATE = "INITIALSTATE"

export const PRODUCTS_INIT = "PRODUCTS/INIT"

export const PRODUCT_TO_ACC = 'PRODUCT/TOACC'
export const PRODUCT_ALERT_TRUE = 'PRODUCT/ALERT/TRUE'
export const PRODUCT_ALERT_FALSE = 'PRODUCT/ALERT/FALSE'
export const PRODUCT_IMG_CHANGE = "PRODUCT/IMG/CHANGE"

export const PRODUCTS_FILTER = 'PRODUCTS/FILTER'

export const USER_CHANGE = "USER/CHANGE"

export const ACC_FULL_CHANGE = "ACC/FULL/CHANGE"

export const BASKET_CHANGE = 'ACC/BASKET/CHANGE'
export const BASKET_DELETE = 'ACC/BASKET/DELETE'
export const BASKET_DELETE_ITEM = "ACC/BASKET-ITEM/DELETE"

export const LIKES_CHANGE = 'ACC/LIKES/CHANGE'
export const LIKES_DELETE = 'ACC/LIKES/DELETE'

export const ORDER_CHANGE = 'ACC/ORDER/CHANGE'
export const ORDER_DELETE = 'ACC/ORDER/DELETE'

export const ACC_ALERT_SHOW = "ACC/ALERT/SHOW"
export const ACC_ALERT_HIDE = "ACC/ALERT/HIDE"
export const ACC_MINI_OPEN = "ACC/MINI/OPEN"

export const LOCATION_FROM_CHANGE = 'PAGES/LOCATION/FROM/CHANGE'

export const FILTER_CATALOGE = 'FILTER/CATALOGE'